### PR TITLE
6thOct-7.py

### PR DESCRIPTION
**Pull request by ayush-mishra-git**

### CODE REVIEW

**Comment by vibrantachintya** [comment]
Rename your file to 6thOct-7.py

**Comment by ayush-mishra-git** [comment]
Done.

**Comment by vibrantachintya** [comment]
It is still showing conflict, I am not able to merge

**Comment by ayush-mishra-git** [comment]
I have resolved kindly check

**Comment by vibrantachintya** [comment]
YP

Don't forget to 'star' this repo and join our Telegram group! http://bit.ly/TwowaitsTelegram

**Pull request merged**
