### PR TITLE
22ndOct.cpp Permutations of a String (without rep)

### PR DESCRIPTION
**Pull request by Ocoderdude**
* Without string as parameter to function
* Without repeating any character in a string.

### CODE REVIEW

**Comment by vibrantachintya** [comment]
Rename to 22ndOct-2.cpp

**Comment by Ocoderdude** [comment]
Hi @vibrantachintya , I was the first one who wrote the code for this program. I did PR before others. 

Why haven't you merged mine first and want me to rename it?

**Comment by Ocoderdude** [comment]
https://github.com/twowaits/make-pull-request/issues/569#issuecomment-714391926

**Comment by vibrantachintya** [comment]
You have to rename the file, if you don't before 8 PM. I will reject this PR.

**Comment by Ocoderdude** [comment]
> You have to rename the file, if you don't before 8 PM. I will reject this PR.

This is so rude behaviour :(

**Comment by Ocoderdude** [comment]
I am new to open source and you behave like this with me?

**Comment by Ocoderdude** [comment]
@hitman-samrath , This happened because of you

**Comment by Ocoderdude** [comment]
I think the deadline was 8 PM

**Comment by Ocoderdude** [comment]
> You have to rename the file, if you don't before 8 PM. I will reject this PR.

I think the deadline was 8 PM

**Pull request closed without merging**
