### PR TITLE
MY_HOLLOW_PYRAMID

### PR DESCRIPTION
**Pull request by ekanshverma5**
I have completed the function which prints a 'Hollow Pyramid' of size 'N'. For this I have used a user-defined class 'FastReader' and have used 'StringBuilder' class to store the pattern.

### CODE REVIEW

**Comment by vibrantachintya** [comment]
Add file in python directory and update file name accordingly

**Comment by ekanshverma5** [comment]
Do I need to code it in python or just add the same code in python directory?

**Comment by ekanshverma5** [comment]
Sir! @vibrantachintya  I have committed the python code for 'Hollow Pyramid'.

**Comment by vibrantachintya** [comment]
Create a new file, you cant edit exsting one

**Pull request closed without merging**
