### PR TITLE
26Sept8.cpp

### PR DESCRIPTION
**Pull request by geetika005**
C++ binary conversion question

### CODE REVIEW

**Comment by vibrantachintya** [comment]
Rename file as per rules described in issue desc.

**Comment by geetika005** [comment]
Renamed sir

**Comment by geetika005** [comment]
Please review my pr sir

**Comment by vibrantachintya** [comment]
Still not correct, kindly read issue description carefully.

**Comment by geetika005** [comment]
Done sir

**Comment by vibrantachintya** [comment]
Good

**Pull request merged**
