### PR TITLE
Create 7thOct-2.cpp

### PR DESCRIPTION
**Pull request by Rsr0**
solution for issue #147.

### CODE REVIEW

**Comment by vibrantachintya** [comment]
Check your code, there are some errors, refer to sample I/O provided and attack screenshots for input : "122232"

**Comment by Rsr0** [comment]
Sir can u elaborate the errors?

**Comment by vibrantachintya** [comment]
Fix error of code showing 1 lac as 1 lacs.

**Comment by Rsr0** [comment]
fixed error ! :-)

**Comment by vibrantachintya** [comment]
Don't forget to star the repo

**Comment by Rsr0** [comment]
yeah sure and thanks for help.

**Pull request merged**
