### PR TITLE
c++_program_to_find_gcd_of_factorial_of_two_numbers

### PR DESCRIPTION
**Pull request by YUGANSHCHAUHAN**
c++_program_to_find_gcd_of_factorial_of_two_numbers

### CODE REVIEW

**Comment by vibrantachintya** [comment]
Add in folder of Python, your file

**Comment by YUGANSHCHAUHAN** [comment]
should i add it in python or c++ folder. The code is in c++

**Comment by vibrantachintya** [comment]
C++

**Comment by YUGANSHCHAUHAN** [comment]
I have changed the folder. Please merge it

**Pull request merged**
