### PR TITLE
Added C++ program for fibonacci series with a twist

### PR DESCRIPTION
**Pull request by jahnavi-yelamanchi**
This is a c++ program that takes a number 'n' and prints the fibonacci series upto n while replacing prime numbers and all multiples of 5 by 0.

### CODE REVIEW

**Comment by jahnavi-yelamanchi** [comment]
Created pull request :)

**Comment by jahnavi-yelamanchi** [comment]
#743 added c++ program

**Comment by vibrantachintya** [comment]
Good work. I am merging your PR.

Do give us a star by hitting the star button of this repo!

**Comment by jahnavi-yelamanchi** [comment]
Thank you!

**Pull request merged**
