### PR TITLE
add tathastu's (why_tathasu) page replica

### LINKED ISSUE #747: 1st Oct : Make any 1 Web Page out of this Website
## Tathastu Website

Today we will be making the website of Tathastu. Tathastu is a skill learning platform which provides a variety of courses to help students secure internships & jobs.

There are 4 pages in it. You have to make only 1 page out of these 4. You can make any one of your choice.

You can take all the necessary images from our [Website](http://tathastu.twowaits.in/)

Page 1 : intro.html

Page 2 : why_tathastu.html

Page 3 : courses.html

Page 4 : feedback.html

Rules :
- You have to choose any one page out of it and work on it.
- Write all your CSS in the same HTML file. You can either write in <style> tag or inline CSS.
- No need to wait for getting assigned, you can go ahead attempt the issues and raise a PR by 10 AM 2nd oct.
- We will review any comments or PRs at 5 PM & 10 PM on 1st Oct, will give feedback if needed.

How to name your file?
- Go to folder : "/HTML CSS/2021/"
- Take File's name, i.e. intro.
- Take your GitHUB username id like "hrithik339", "hacker-boy", etc or anything which you have.
- File extension = ".html" in this issue.

Combine all 3 to get your file name : Page Name + "_" + Username + File Extension, ex. "intro_hrithik339.html". Create this file in above mentioned folder only "/HTML CSS/2021/".

This will ensure no file will be conflict and any number of contributors can work on the same issue.

If you have any query ask in comments below, kindly follow this pattern strictly.

You can join our Whatsapp group to get instant support : [Link to Whatsapp Group](https://chat.whatsapp.com/BtRr45YEgxI5tQCsaTDMzM)

### PR DESCRIPTION
**Pull request by SwapnilSoni1999**
- Added filename as mentioned in issue
- made same replica except font
- Responsiveness: Works!

### CODE REVIEW

**Review by salman0ansari — APPROVED** [review]
Looks good to me.

**Comment by vibrantachintya** [comment]
Unlink this PR with issue.

I will merge it when you do!

**Comment by SwapnilSoni1999** [comment]
Alright done

> Unlink this PR with issue.
> 
> I will merge it when you do!

Done sir!

**Comment by vibrantachintya** [comment]
Good work. I am merging your PR.

Do give us a star by hitting the star button of this repo!

**Comment by SwapnilSoni1999** [comment]
Sure thing <3

**Comment by mRahulRoy** [comment]
how images will be opened.
or i just has to submit the html/css code.
please reply

**Pull request merged**
