### PR TITLE
created 1stOct_atharval1.cpp

### PR DESCRIPTION
**Pull request by atharval1**
Added a program of Fibonacci Series with a Twist with a file name 1stOct_atharval1.cpp

### CODE REVIEW

**Comment by atharval1** [comment]
added a program of zig zag problem

**Review by atharval1 — COMMENTED** [review]
i have added a program of second octomber zig zag problem

**Review by codenipun — COMMENTED** [review]
@atharval1 Your file name is not correct .Please read the issue discription once again

**Comment by atharval1** [comment]
> @atharval1 Your file name is not correct .Please read the issue discription once again

as per description i have created correct file name 2ndOct_atharval1.cpp  and 1stOct_atharval1.cpp i have added two pr as per description i have written correct file name if not please help me what can i do

**Comment by atharval1** [comment]
please help me what can i do

**Comment by codenipun** [comment]
@atharval1  see others pull request which are accepted. you will definitely get an idea

**Comment by atharval1** [comment]
> @atharval1 see others pull request which are accepted. you will definitely get an idea

sir i have check other pull request sir all are same sir i don't know which mistake will be happened

**Comment by atharval1** [comment]
now you can check all are correct or not as per your description i have done everything

**Comment by atharval1** [comment]
now please check updated thing i have do some changes

**Comment by vibrantachintya** [comment]
Good work. I am merging your PR.

Do give us a star by hitting the star button of this repo!

**Pull request merged**
