### PR TITLE
9thOct-3.py

### PR DESCRIPTION
**Pull request by Harshit1487**
Complete today task.

### CODE REVIEW

**Comment by vibrantachintya** [comment]
Add in Python folder, name accordingly.

**Comment by Harshit1487** [comment]
Ok

**Comment by Harshit1487** [comment]
I change file name. I does not know how to change folder.

**Comment by Harshit1487** [comment]
Can I make new pull request.

**Comment by vibrantachintya** [comment]
Yes make new. Just add folder name and / in file name.

**Pull request closed without merging**
