### PR TITLE
Added solution for Fibonacci Series with a Twist

### PR DESCRIPTION
**Pull request by alkatrivedi**
Implementation in C++ for issue #88. Thank you!

### CODE REVIEW

**Comment by vibrantachintya** [comment]
Rename file to 6thOct-6.cpp

**Comment by alkatrivedi** [comment]
Done that.

**Comment by vibrantachintya** [comment]
Don't forget to 'star' this repo and join our Telegram group! http://bit.ly/TwowaitsTelegram

**Comment by alkatrivedi** [comment]
Yeah sure. Thanks for merging:)

**Pull request merged**
