### PR TITLE
Create a java program for display Fibonacci Series with a Twist

### PR DESCRIPTION
**Pull request by LakshithaSamod**
I Created a java program for the display Fibonacci Series. Also, I have implemented the below functions as you requested.

    -Take input the value of 'n', up to which you will print.
    -Print the Fibonacci Series up to n while replacing prime numbers, all multiples of 5 by 0.

### CODE REVIEW

**Comment by vibrantachintya** [comment]
Empty file? Kindly add code as well.

You have time till 2nd Oct, 10 AM.

**Review by LakshithaSamod — COMMENTED** [review]
Edited The file

**Comment by LakshithaSamod** [comment]
Sorry, There were some errors when pulling the PR. I have edited the file. Please check the file again.

**Comment by LakshithaSamod** [comment]
> 
> 
> Empty file? Kindly add code as well.
> 
> You have time till 2nd Oct, 10 AM.

Sorry, There were some errors when pulling the PR. I have edited the file. Please check the file again.

**Comment by vibrantachintya** [comment]
Good work. I am merging your PR.

Do give us a star by hitting the star button of this repo!

**Comment by LakshithaSamod** [comment]
> 
> 
> Good work. I am merging your PR.
> 
> Do give us a star by hitting the star button of this repo!

Sure Thanks !

**Pull request merged**
