### PR TITLE
Implemented zigzag pattern

### PR DESCRIPTION
**Pull request by KunalJaiswal-17**

### CODE REVIEW

**Comment by anirudh15-cyber** [comment]
code is working fine..

**Comment by anirudh15-cyber** [comment]
change your name according to the guidelines to be qualify.Team Two-Waits.

**Comment by KunalJaiswal-17** [comment]
> change your name according to the guidelines to be qualify.Team Two-Waits.

file name?
if you're talking about file name then it is 2ndOct_KunalJaiswal-17.py
i guess it is correct

**Comment by vibrantachintya** [comment]
Good work. I am merging your PR.

But it will not be considered for Hacktoberfest as our Project is excluded from this contest.

As a gesture we are providing a certificate of contribution for every successful PR. If you want that kindly Whatsapp me on 9456056603 with this PR id.

Do give us a star by hitting the star button of this repo!

**Pull request merged**
