### PR TITLE
1stOct_harsh-solanki21 hacktoberfest 2021

### PR DESCRIPTION
**Pull request by harsh-solanki21**
Solution of Fibonacci series with a twist problem

### CODE REVIEW

**Review by arya177 — CHANGES_REQUESTED** [review]
Variable 'c' is not declared. Please do the required changes.

**Comment by harsh-solanki21** [comment]
It is already declared. Otherwise code won't execute.

**Review by arya177 — COMMENTED** [review]
Yes, it is. This PR seems fine. Satisfies required conditions.

**Comment by vibrantachintya** [comment]
Good work. I am merging your PR.

Do give us a star by hitting the star button of this repo!

**Comment by harsh-solanki21** [comment]
Thanks a lot. I support your work by giving this repo a star and looking forward to more such problems to contribute.

**Pull request merged**
