### PR TITLE
2ndOct_Tanushree-Ghosh.java

### PR DESCRIPTION
**Pull request by Tanushree-Ghosh**

### CODE REVIEW

**Review by Yash-Wasalwar-07 — CHANGES_REQUESTED** [review]
Hi there👋,
I am Yash from twowaits,

Your output is not satisfying the conditions (Hint: Check the spacing of elements in matrix properly)

**Review by Yash-Wasalwar-07 — COMMENTED** [review]
Yes, it's ok now!!

**Comment by Tanushree-Ghosh** [comment]
@Yash-Wasalwar-07 Thanks For your Guidance.

**Comment by vibrantachintya** [comment]
Good work. I am merging your PR.

But it will not be considered for Hacktoberfest as our Project is excluded from this contest.

As a gesture we are providing a certificate of contribution for every successful PR. If you want that kindly Whatsapp me on 9456056603 with this PR id.

Do give us a star by hitting the star button of this repo!

**Pull request merged**
