### PR TITLE
created 1stOctober_santoshkakkera.cpp

### PR DESCRIPTION
**Pull request by santoshkakkera**
sir i have added 0 in the fibonacci series.

### CODE REVIEW

**Review by Positron007 — COMMENTED** [review]
There are a few lines which could have been avoided. But code serves the purpose.

**Comment by santoshkakkera** [comment]
@Positron007 is enough to get merged

**Comment by santoshkakkera** [comment]
or may i change the code.but i think if modified also almost logic remains same . could you please verify it.

**Comment by vibrantachintya** [comment]
Good work. I am merging your PR.

Do give us a star by hitting the star button of this repo!

**Pull request merged**
