### PR TITLE
Fixed Issue #1505

### LINKED ISSUE #1505: 3rd Oct : Write a Function in C++ to achieve below functionality
This repo is excluded from Hacktoberfest. But you can solve below issue for practice and win a Certificate of Appreciation for contributing to Twowaits Repo.

## ZigZag Problem

Add following functionalities to it :

- Take input of number of rows and columns.
- Print the following zigzag pattern.

Sample Input :
7 16

Sample Output :
<pre>
1                       13 
  2                  12  14
    3              11        15
      4          10             16
        5      9
          6  8
            7
</pre>

- No need to wait for getting assigned, you can go ahead attempt the issues and raise a PR by 10 AM 4th Oct.
- We will review any comments or PRs at 5 PM & 10 PM on 3rd Oct, will give feedback if needed.

How to name your file?
- Go to folder : "/C++/2021/"
- Take today's date, i.e. 3rdOct
- Take your GitHUB username id like "hrithik339", "hacker-boy", etc or anything which you have.
- File extension = ".cpp" in this issue.

Combine all 3 to get your file name : Date + "_" + Username + File Extension, ex. "3rdOct_hrithik339.cpp". Create this file in above mentioned folder only "/C++/2021/".

This will ensure no file will be conflict and any number of contributors can work on the same issue.

If you have any query ask in comments below, kindly follow this pattern strictly.

You can join our Whatsapp group to get instant support : [Link to Whatsapp Group](https://chat.whatsapp.com/IMhVQFFE3paCTIEQKukN7J)

### PR DESCRIPTION
**Pull request by PrerakMathur20**
Fixes #1505
Efficient solution to the ZigZag problem.

### CODE REVIEW

**Comment by Vishal-Aggarwal0305** [comment]
good

**Comment by PrerakMathur20** [comment]
Repaired code for some corner cases.

**Comment by PrerakMathur20** [comment]
Added solution for same in **JAVA**.  Fixed #1508

**Comment by vibrantachintya** [comment]
Good work. I am merging your PR.

But it will not be considered for Hacktoberfest as our Project is excluded from this contest.

As a gesture we are providing a certificate of contribution for every successful PR. If you want that kindly Whatsapp me on 9456056603 with this PR id.

Do give us a star by hitting the star button of this repo!

**Pull request merged**
