### PR TITLE
C++ Code for Fibonacci Series with a Twist

### PR DESCRIPTION
**Pull request by Shyam-2001**

### CODE REVIEW

**Comment by swapnil604** [comment]
Correct the file name.

**Comment by vibrantachintya** [comment]
@Shyam-2001 Fix filename as per issue desc.

**Comment by Shyam-2001** [comment]
Sir i am not getting it whats wrong in my file name

**Comment by vibrantachintya** [comment]
Name is 1stOct and not 2ndOct

**Comment by Shyam-2001** [comment]
Means you rejected or accepted.?

**Pull request closed without merging**
