### PR TITLE
Added C++ solution to Fibonacci sequence with a twist 

### PR DESCRIPTION
**Pull request by basic-bhavya**

### CODE REVIEW

**Comment by swapnil604** [comment]
Your code shows errors plz fix them.

**Comment by vibrantachintya** [comment]
@basic-bhavya  Fix fast

**Comment by basic-bhavya** [comment]
> @basic-bhavya  Fix fast

Ok fixing

**Comment by basic-bhavya** [comment]
Please confirm. Thanks.

**Comment by swapnil604** [comment]
It works now, great!

**Comment by vibrantachintya** [comment]
Good work. I am merging your PR.

Do give us a star by hitting the star button of this repo!

**Pull request merged**
