### PR TITLE
Hollow-pyramid

### PR DESCRIPTION
**Pull request by Aditya489**
8thOct py - make-pull-request-2 - Visual Studio Code 08-10-2020 19_41_54
 did a code to create a pattern of hollow pyramid and the input is taken from the user

### CODE REVIEW

**Comment by vibrantachintya** [comment]
Good

Add file in Python folder and with latest name!

**Comment by Aditya489** [comment]
Isn't the file already added to the master branch?

**Comment by Aditya489** [comment]
I'm kinda new to GitHub and trying to learn if you can assist me in how to do that! Or you can merge it, like you did previously?

**Comment by Aditya489** [comment]
with latest name? do you meant by 8thOct-13.py like that? or something else?

**Pull request merged**
