### PR TITLE
Create 1stOct_Kritika6100.java

### PR DESCRIPTION
**Pull request by Kritika6100**
Hey, I have fixed the issue as you wanted. Kindly merge it.

### CODE REVIEW

**Review by Yash-Wasalwar-07 — APPROVED** [review]
Hi there! 
Your output is correct
Satisfies the guidelines

I want to give useful feedback -
Next time make your code more appealing, like use functions to keep your code clean.

Keep contributing!🙌
Also, share this repo with your friends!

**Comment by Kritika6100** [comment]
> Hi there! Your output is correct Satisfies the guidelines
> 
> I want to give useful feedback - Next time make your code more appealing, like use functions to keep your code clean.
> 
> Keep contributing!🙌 Also, share this repo with your friends!

Okay. Can you tell after I have requested the pull request on my Hacktoberfest page it's not showing anything in progress?

**Comment by Yash-Wasalwar-07** [comment]
It seems like Hacktoberfest website is being hanged !!, don't worry it will be up soon.

Same condition is with mine!!
________________________________

**Comment by vibrantachintya** [comment]
Good work. I am merging your PR.

Do give us a star by hitting the star button of this repo!

**Comment by Kritika6100** [comment]
Thank you sir

**Pull request merged**
