### PR TITLE
Added Java File for issue : Fibonacci series with a twist

### PR DESCRIPTION
**Pull request by subhradwip01**
Added Java File for issue #744  : Write a Function in JAVA to achieve the below functionality.

### CODE REVIEW

**Review by krishnavpai — COMMENTED** [review]
Satisfies the criteria.
Keep contributing.
Also, share this repo with your friends.

**Comment by subhradwip01** [comment]
@krishnavpai can you please add the label hacktoberfest-accepted ?

**Comment by subhradwip01** [comment]
Is it possible to merged?

**Comment by vibrantachintya** [comment]
Good work. I am merging your PR.

Do give us a star by hitting the star button of this repo!

**Pull request merged**
