### PR TITLE
twistedFiboJava 

### PR DESCRIPTION
**Pull request by SudhanshuBlaze**
This is the solution to the 'twistedFibo' problem in Java as a part of Hacktober fest '21

### CODE REVIEW

**Review by krishnavpai — COMMENTED** [review]
Correct output.
Satisfies the criteria.
Hope you have written it honestly.
Keep contributing.
Also, share this repo with your friends.

**Comment by SudhanshuBlaze** [comment]
Please merge this PR as it's giving correct output @krishnavpai

**Comment by vibrantachintya** [comment]
Good work. I am merging your PR.

Do give us a star by hitting the star button of this repo!

**Comment by SudhanshuBlaze** [comment]
Screenshot 2021-10-02 at 8 19 33 PM
Why it is showing like this? Is this project excluded from Hacktober Fest '21?

**Pull request merged**
