### PR TITLE
10thOct-3.py

### PR DESCRIPTION
**Pull request by Harshit1487**
10thOct-3.py

### CODE REVIEW

**Comment by vibrantachintya** [comment]
You have added file for 9th Oct as well. We are not accepting that.

Remove it will accept then,

**Comment by Harshit1487** [comment]
How I remove 9Oct file ?

**Comment by vibrantachintya** [comment]
Just delete from your directory.

**Comment by Harshit1487** [comment]
If I delete 9 Oct file then it will count in Hactoberfest or not ??

**Comment by vibrantachintya** [comment]
Yes

**Comment by vibrantachintya** [comment]
Don't forget to star the repo!

**Pull request merged**
