### PR TITLE
Created the html page for why_tathastu

### PR DESCRIPTION
**Pull request by Ayush21042002**
**The webpage is for the issue #747**
Preview is given below:
image

### CODE REVIEW

**Comment by mRahulRoy** [comment]
how to submit html code and pictures used in site
please let me know. i dont know how to submit images used in the site.
becouse author has told us to make a one file only

**Comment by Ayush21042002** [comment]
> how to submit html code and pictures used in site please let me know. i dont know how to submit images used in the site. becouse author has told us to make a one file only

In the issue #747 it is written to get the image from their website

**Comment by mRahulRoy** [comment]
ice_screenshot_20211001-132737

**Comment by mRahulRoy** [comment]
Preview !!
Sir please merge my code . This is what i made.
ice_screenshot_20211001-132737
e.

**Comment by vibrantachintya** [comment]
Good work. I am merging your PR.

Do give us a star by hitting the star button of this repo!

**Comment by mRahulRoy** [comment]
> 
> 
> Good work. I am merging your PR.
> 
> Do give us a star by hitting the star button of this repo!

already done sir...

**Pull request merged**
