### PR TITLE
1stOct_durgesh-4526.cpp

### PR DESCRIPTION
**Pull request by durgesh-4526**

### CODE REVIEW

**Comment by vibrantachintya** [comment]
Rename filename as per rules mentioned in issue description.

**Comment by durgesh-4526** [comment]
> Rename filename as per rules mentioned in issue description.

@vibrantachintya As per your instruction I have renamed my file

**Comment by vibrantachintya** [comment]
You have changed title of PR..You have to change the file's name...which you have named 1.

**Comment by durgesh-4526** [comment]
> You have changed title of PR..You have to change the file's name...which you have named 1.

@vibrantachintya kindly check it once I have renamed it . Thanks for your guidance

**Comment by vibrantachintya** [comment]
Good work. I am merging your PR.

But it will not be considered for Hacktoberfest as our Project is excluded from this contest.

As a gesture we are providing a certificate of contribution for every successful PR. If you want that kindly Whatsapp me on 9456056603 with this PR id.

Do give us a star by hitting the star button of this repo!

**Pull request merged**
