### PR TITLE
Create 1stOct_akshat-kumar2109.java

### PR DESCRIPTION
**Pull request by akshat-kumar2109**
Added 1stOct_akshat-kumar2109.java

### CODE REVIEW

**Review by krishnavpai — COMMENTED** [review]
Correct output.
Satisfies the criteria.
Hope you have written it honestly.

Keep contributing.
Also, share this repo with your friends.

**Comment by akshat-kumar2109** [comment]
when it will be merged??

**Comment by krishnavpai** [comment]
> when it will be merged??

Yes, your PR will be accepted. Don't worry.
We all are here to learn and grow.

**Comment by vibrantachintya** [comment]
Good work. I am merging your PR.

Do give us a star by hitting the star button of this repo!

**Pull request merged**
