### PR TITLE
added Tathastu's 'intro_tathasu' page replica

### PR DESCRIPTION
**Pull request by tamojeetK**
▪️ 'Filename' as mentioned in the issue
▪️ Made same replica

### CODE REVIEW

**Comment by tamojeetK** [comment]
Preview of the Page - 
Screenshot 2021-10-01 093751

**Comment by tamojeetK** [comment]
@vibrantachintya Sir pls check my PR and let me know if something is to be done.

**Comment by vibrantachintya** [comment]
Good work. I am merging your PR.

Do give us a star by hitting the star button of this repo!

**Comment by tamojeetK** [comment]
> Good work. I am merging your PR.
> 
> Do give us a star by hitting the star button of this repo!

Thank u Sir and Sure I'm gonna Star it. ✨😊👍

**Pull request merged**
