### PR TITLE
Added 7thOct.py

### PR DESCRIPTION
**Pull request by yash5015**
Convert Digits into Words

### CODE REVIEW

**Comment by vibrantachintya** [comment]
Check your code, there are some errors, refer to sample I/O provided and attack screenshots for input : "122232"

**Comment by yash5015** [comment]
Sir it works

**Comment by yash5015** [comment]
Sir, what about my pull request? Will it merge?(#hactoberfest).

**Comment by vibrantachintya** [comment]
We have run your code, its not passing all use cases. If you don't update code by 11 am tomorrow. We will close this PR,

**Pull request closed without merging**
