### PR TITLE
Create 2ndOct_technicalreju.cpp

### PR DESCRIPTION
**Pull request by technicalreju**
2nd October Zig-Zag Problem in cpp.

### CODE REVIEW

**Comment by Vishal-Aggarwal0305** [comment]
Nice Work Reviewed

--Twowaits Employee

**Comment by technicalreju** [comment]
I kindly request the maintainer merge my request.

**Comment by vibrantachintya** [comment]
Good work. I am merging your PR.

But it will not be considered for Hacktoberfest as our Project is excluded from this contest.

As a gesture we are providing a certificate of contribution for every successful PR. If you want that kindly Whatsapp me on 9456056603 with this PR id.

Do give us a star by hitting the star button of this repo!

**Comment by technicalreju** [comment]
Thank You Sir.
I am happy that you merged my PR. I think knowledge is more valuable than a T-Shirt though it was my first PR of Hacktoberfest 2021. All the way I came to you through Youtube and also a good repo for DSA problem.

Happy Meeting with you. Go ahead and achieve success in life.
Best wishes

**Pull request merged**
